table sales
	lineageTag: 3de901f6-8b86-4346-9ca9-b0b4863577fa

	column Sale_ID
		dataType: int64
		formatString: 0
		lineageTag: cf08f89c-8879-43cf-81b7-485de9595850
		summarizeBy: count
		sourceColumn: Sale_ID

		annotation SummarizationSetBy = Automatic

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: dea9d830-5656-404f-9db6-f690dafdcea8
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Store_ID
		dataType: int64
		formatString: 0
		lineageTag: d06f90d7-a7c2-48d4-b7bd-9e03db5cfbf3
		summarizeBy: none
		sourceColumn: Store_ID

		annotation SummarizationSetBy = Automatic

	column Product_ID
		dataType: int64
		formatString: 0
		lineageTag: e21873b4-c807-48b4-93fe-efd8bbce722f
		summarizeBy: none
		sourceColumn: Product_ID

		annotation SummarizationSetBy = Automatic

	column Units
		dataType: int64
		formatString: 0
		lineageTag: 999df31a-30e8-4c39-ade0-ccaae2df9d79
		summarizeBy: sum
		sourceColumn: Units

		annotation SummarizationSetBy = Automatic

	partition sales = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("E:\Data\Maven Toys Data\sales.csv"), [Delimiter = ",", Columns = 5, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Sale_ID", Int64.Type}, {"Date", type date}, {"Store_ID", Int64.Type}, {"Product_ID", Int64.Type}, {"Units", Int64.Type}})
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

